# Generated by Django 5.0.2 on 2024-02-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemist_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
