# Generated by Django 5.0.2 on 2024-02-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemist_backend', '0002_sales_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='category',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
